# “Вычисления с помощью Numpy”

# Задание 1

In [ ]:
import numpy as np

In [65]:
b = np.array([[1,2,3,3,1],
              [6,8,11,10,7]]).transpose()

In [66]:
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
mean_a = np.mean(b, axis =0)

In [68]:
mean_a

array([2. , 8.4])

# Задание 2

In [69]:
a_centered = b - mean_a

In [70]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [71]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [72]:
a_centered_sp

8.0

In [73]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

# Задание 4**

In [74]:
np.cov(b.T)[0, 1]

2.0

# Тема “Работа с данными в Pandas”

# Задание 1

In [76]:
import pandas as pd

In [77]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                       columns=['author_id', 'author_name'])

In [86]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                        'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 
                                       'Толстый и тонкий', 'Дама с собачкой', 
                                       'Гроза', 'Таланты и поклонники'],
                        'price':[450, 300, 350, 500, 450, 370, 29]}, 
                       columns=['author_id', 'book_title', 'price'])

In [87]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники     29

# Задание 2

In [89]:
authors_price = pd.merge (authors , book, on = 'author_id' , how - 'inner')

In [90]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники     29

# Задание 3

In [91]:
top5 = authors_price.nlargest(5, 'price')

In [92]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

# Задание 4

In [98]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

In [99]:
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский         29       370  199.500000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000